#listado de partidas
CAMBIO_LISTAR_PARTIDA = "A"
#lobby
CAMBIO_ESTADO_LOBBY = "B"
ABANDONO_CREADOR = "I"
PARTIDA_INICIADA = "L"
#juego
CAMBIO_ESTADO_JUEGO= "C"
CAMBIO_ESTADO_JUGADOR = "D"
HABILITADO_ROBAR_CARTA = "E" 
HABILITADO_JUGAR_DESCARTADO = "F"
HABILITADO_INTERCAMBIO = "G"
HABILITADO_R_INTERCAMBIO = "H"
HABILITADO_D_INTERCAMBIO = "N"
HABILITA_JUGAR_DEFENSA = "J"
PARTIDA_FINALIZADA = "K"
#chat
MENSAJE_NUEVO = "M"
